-   id: import-sort-cli
    name: import-sort-cli
    entry: import-sort-cli
    language: node
    'types': [javascript]
    args: ["-i"]
    require_serial: false
    additional_dependencies: ["import-sort-cli@2.4.0"]
    minimum_pre_commit_version: '0'
